Repository Manojkumarchow/chill-app, pull requests merged in 2022-12, with the labels that each got.

#1 Initial Commit 🚀
  .DS_Store
  .idea/.gitignore
  .idea/chill-app.iml
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  .idea/jpa-buddy.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  chill-react/.gitignore
  chill-react/README.md
  chill-react/package-lock.json
  chill-react/package.json
  chill-react/public/favicon.ico
  chill-react/public/index.html
  chill-react/public/logo192.png
  chill-react/public/logo512.png
  chill-react/public/manifest.json
  chill-react/public/robots.txt
  chill-react/src/App.css
  chill-react/src/App.js
  chill-react/src/App.test.js
  chill-react/src/component/ListUsersComponent.js
  chill-react/src/component/UserComponent.js
  chill-react/src/component/UserDataService.js
  chill-react/src/index.css
  chill-react/src/index.js
  chill-react/src/logo.svg
  chill-react/src/reportWebVitals.js
  chill-react/src/setupTests.js
  hiring/.gitignore
  hiring/.mvn/wrapper/maven-wrapper.jar
  hiring/.mvn/wrapper/maven-wrapper.properties
  hiring/mvnw
  hiring/mvnw.cmd
  hiring/pom.xml
  hiring/src/main/java/hiring/HiringApplication.java
  hiring/src/main/java/hiring/controller/UserController.java
  hiring/src/main/java/hiring/model/User.java
  hiring/src/main/java/hiring/service/ApplicantService.java
  hiring/src/main/java/hiring/service/UserService.java
  hiring/src/main/resources/application.properties
  hiring/src/test/java/hiring/HiringApplicationTests.java
  sql/user.sql
Labels: backend, database

#2 Down merging with main branch
  .github/workflows/maven.yml
  .github/workflows/react-js.yml
Labels: enhancement

#4 Down Merging
  .DS_Store
  .github/workflows/maven.yml
  backend/.gitignore
  backend/.mvn/wrapper/maven-wrapper.jar
  backend/.mvn/wrapper/maven-wrapper.properties
  backend/mvnw
  backend/mvnw.cmd
  backend/pom.xml
  backend/src/bin/com/example/demo/DemoApplication.class
  backend/src/bin/com/example/demo/DemoApplicationTests.class
  backend/src/bin/com/example/demo/controllers/UserController.class
  backend/src/bin/com/example/demo/models/User.class
  backend/src/bin/com/example/demo/services/UserService.class
  backend/src/main/java/com/example/demo/DemoApplication.java
  backend/src/main/java/com/example/demo/controllers/UserController.java
  backend/src/main/java/com/example/demo/models/User.java
  backend/src/main/java/com/example/demo/services/UserService.java
  backend/src/main/resources/application.properties
  backend/src/test/java/com/example/demo/DemoApplicationTests.java
  hiring/pom.xml
  hiring/src/.project
  hiring/src/main/java/hiring/HiringApplication.java
  hiring/src/main/java/hiring/controller/UserController.java
  hiring/src/main/java/hiring/model/User.java
  hiring/src/main/java/hiring/service/ApplicantService.java
  hiring/src/main/java/hiring/service/UserService.java
Labels: backend
